<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE edicionesAranda[
<!ELEMENT edicionesAranda(informe)>
<!ELEMENT informe(descripcion,fecha_informe,dato)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha_informe (#PCDATA)>
<!ELEMENT dato(region,trimestres,libros)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT trimestres(trimestre)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT libros(libros_vendidos)>
<!ELEMENT libros_vendidos (#PCDATA)>
]>

<edicionesAranda>
    <informe>
        <descripcion> informe de ventas para las regiones Norte, Centro y Sur</descripcion>
        <fecha_informe>30/12/2009</fecha_informe>
        <dato>
            <region>Norte</region>
            <trimestres>
                <trimestre>1</trimestre>
                <trimestre>2</trimestre>
                <trimestre>3</trimestre>
                <trimestre>4</trimestre>
            </trimestres>
            <libros>
                <libros_vendidos>24000</libros_vendidos>
                <libros_vendidos>38600</libros_vendidos>
                <libros_vendidos>NO_INFO</libros_vendidos>
                <libros_vendidos>NO_INFO</libros_vendidos>
            </libros>
        </dato>
        <dato>
            <region>Centro</region>
            <trimestres>
                <trimestre>1</trimestre>
                <trimestre>2</trimestre>
                <trimestre>3</trimestre>
                <trimestre>4</trimestre>
            </trimestres>
            <libros>
                <libros_vendidos>NO_INFO</libros_vendidos>
                <libros_vendidos>16080</libros_vendidos>
                <libros_vendidos>25000</libros_vendidos>
                <libros_vendidos>29000</libros_vendidos>
            </libros>
        </dato>
        <dato>
            <region>Sur</region>
            <trimestres>
                <trimestre>1</trimestre>
                <trimestre>2</trimestre>
                <trimestre>3</trimestre>
                <trimestre>4</trimestre>
            </trimestres>
            <libros>
                <libros_vendidos>27000</libros_vendidos>
                <libros_vendidos>31400</libros_vendidos>
                <libros_vendidos>40100</libros_vendidos>
                <libros_vendidos>30000</libros_vendidos>
            </libros>
        </dato>
    </informe>
</edicionesAranda>