=== Davidguijo18/CursoDAW/Primer Año/Lenguaje de Marcas/1 evaluacion/xml y dtd/Actividad 14(Externa).dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<DOCTYPE matricula[
<!ELEMENT matricula(personal,pago)>
<!ELEMENT personal(dni,nombre,titulacion,curso_academico,domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios(domicilio)>
<!ATTLIST domicilio (nombre) "familiar" #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT personal(pago)>
<!ELEMENT pago(tipo_matricula)>
<!ELEMENT tipo_matricula(#PCDATA)>
]>

=== Davidguijo18/CursoDAW/Primer Año/Lenguaje de Marcas/1 evaluacion/xml y dtd/Actividad 14(Externa).xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE matricula SYSTEM "Actividad 14(Externa).dtd">
<matricula>
    <personal>
        <dni>99223366M</dni>
        <nombre>Juan Pardo Martin</nombre>
        <titulacion>Ingenieria Informatica</titulacion>
        <curso_academico>1997/1998</curso_academico>
        <domicilios>
            <domicilio tipo="familiar">
                <nombre>C/ Principal n1</nombre>
            </domicilio>
            <domicilio tipo="habitual">
                <nombre>C/ Secundaria n2</nombre>
        </domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Matricula Ordinaria</tipo_matricula>
    </pago>
</matricula>
